# Generated by Django 5.0.3 on 2024-03-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('cedula', models.TextField(max_length=9)),
                ('edad', models.IntegerField(max_length=2)),
                ('telefono', models.TextField(max_length=8)),
                ('correo', models.TextField()),
            ],
        ),
    ]
