# Generated by Django 5.0.3 on 2024-03-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_alter_clientes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
